import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import { AOIContextProvider } from "@/context/myContext";

const inter = Oswald({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ToastContainer } from "react-toastify";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AOIContextProvider>
      <html lang="pt-br">
        <body className={inter.className}>
          <ToastContainer />
          {children}
        </body>
      </html>
    </AOIContextProvider>
  );
}
